version: 1.0.{build}
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"topgearwebsite" /o:"ricardosa1992-github" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=ac1546386a28dfab2048ef9ab9b10b68b09ab8ff"
  - msbuild "Trabalho20172.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=ac1546386a28dfab2048ef9ab9b10b68b09ab8ff"
build:
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: Environment
  name: WebSite
  on:
      branch: master
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: builds-trabalho20172
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
